[book]
authors = ["Robert Hensing", "Various module authors"]
language = "en"
multilingual = false
src = "src"
title = "flake-parts"

[output.html]
git-repository-url = "https://github.com/hercules-ci/flake-parts"
edit-url-template = "https://github.com/hercules-ci/flake.parts-website/edit/main/site/{path}"
additional-js = [ "no-edit-options.js" ]

[output.html.print]
enable = false  # big single page; don't need that
